---
version: "2.1"
services:
  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Zurich
      - MAX_UPLOAD=5000
    volumes:
      - projectsend_config:/config
      - projectsend_data:/data
    ports:
      - "80"
    restart: unless-stopped
  db:
    image: linuxserver/mariadb:latest
    environment:
      - TZ=Europe/Zurich
      - PUID=1000
      - PGID=100
    volumes:
      - projectsend_db_config:/config
    expose:
      - "3306"
    restart: unless-stopped
volumes:
  projectsend_config:
  projectsend_data:
  projectsend_db_config:
